In [1]:
import numpy as np 

from MissingImputer import MissingImputer

In [2]:
X = np.array([
    [3,0, np.nan, np.nan],  # odd: implicit zero
    [2,5, np.nan, np.nan],  # odd: explicit nonzero
    [7,0, 0, np.nan],    # even: average two zeros
    [8,-5, 0, np.nan],   # even: avg zero and neg
    [2,0, 5, np.nan],    # even: avg zero and pos
    [1,4, 5, np.nan],    # even: avg nonzeros
    [-3,-4, -5, np.nan],  # even: avg negatives
    [0,-1, 2, np.nan],   # even: crossing neg and pos
]).transpose()

In [3]:
MissImputer = MissingImputer(ini_fill = True, model_reg = "knn", model_clf = "knn")
MissImputer

MissingImputer(cat_index=None, ini_fill=True, ini_strategy_clf=None,
        ini_strategy_reg=None, max_iter=10, model_clf='knn',
        model_reg='knn', tol=0.001, with_cat=False)

In [4]:
X_trans = MissImputer.fit(X, model_params = {'regressor':{'n_neighbors':1}, 'classifier':{}}).transform(X.copy())

fit:imputed_ini
[[ 3.          2.          7.          8.          2.          1.
  -3.          0.        ]
 [ 0.          5.          0.         -5.          0.          4.
  -4.         -1.        ]
 [ 1.5         3.5         0.          0.          5.          5.
  -5.          2.        ]
 [ 1.5         3.5         2.33333333  1.          2.33333333  3.33333333
  -4.          0.33333333]]
[[ 3.  2.  7.  8.  2.  1. -3.  0.]
 [ 0.  5.  0. -5.  0.  4. -4. -1.]
 [ 0.  5.  0.  0.  5.  5. -5.  2.]
 [ 0.  5.  0.  0.  5.  5. -5.  2.]]
transform:imputed_ini
[[ 3.          2.          7.          8.          2.          1.
  -3.          0.        ]
 [ 0.          5.          0.         -5.          0.          4.
  -4.         -1.        ]
 [ 1.5         3.5         0.          0.          5.          5.
  -5.          2.        ]
 [ 1.5         3.5         2.33333333  1.          2.33333333  3.33333333
  -4.          0.33333333]]


In [5]:
X_trans

array([[ 3.,  2.,  7.,  8.,  2.,  1., -3.,  0.],
       [ 0.,  5.,  0., -5.,  0.,  4., -4., -1.],
       [ 0.,  5.,  0.,  0.,  5.,  5., -5.,  2.],
       [ 0.,  5.,  0.,  0.,  5.,  5., -5.,  2.]])

In [6]:
MissImputer = MissingImputer(ini_fill = True, model_reg = "xgboost", model_clf = "xgboost")
MissImputer

MissingImputer(cat_index=None, ini_fill=True, ini_strategy_clf=None,
        ini_strategy_reg=None, max_iter=10, model_clf='xgboost',
        model_reg='xgboost', tol=0.001, with_cat=False)

In [7]:
X_trans = MissImputer.fit(X).transform(X.copy())

fit:imputed_ini
[[ 3.          2.          7.          8.          2.          1.
  -3.          0.        ]
 [ 0.          5.          0.         -5.          0.          4.
  -4.         -1.        ]
 [ 1.5         3.5         0.          0.          5.          5.
  -5.          2.        ]
 [ 1.5         3.5         2.33333333  1.          2.33333333  3.33333333
  -4.          0.33333333]]
[[ 3.00000000e+00  2.00000000e+00  7.00000000e+00  8.00000000e+00
   2.00000000e+00  1.00000000e+00 -3.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.00000000e+00  0.00000000e+00 -5.00000000e+00
   0.00000000e+00  4.00000000e+00 -4.00000000e+00 -1.00000000e+00]
 [ 2.98519874e+00  1.99351501e+00  0.00000000e+00  0.00000000e+00
   5.00000000e+00  5.00000000e+00 -5.00000000e+00  2.00000000e+00]
 [ 2.98519874e+00  1.99351501e+00  5.04255295e-04  2.96020508e-03
   4.97279835e+00  4.97460890e+00 -4.96920872e+00  1.99111891e+00]]
transform:imputed_ini
[[ 3.          2.          7.          8.       

In [8]:
print(X_trans)

[[ 3.00000000e+00  2.00000000e+00  7.00000000e+00  8.00000000e+00
   2.00000000e+00  1.00000000e+00 -3.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.00000000e+00  0.00000000e+00 -5.00000000e+00
   0.00000000e+00  4.00000000e+00 -4.00000000e+00 -1.00000000e+00]
 [ 2.98519874e+00  1.99351501e+00  0.00000000e+00  0.00000000e+00
   5.00000000e+00  5.00000000e+00 -5.00000000e+00  2.00000000e+00]
 [ 2.98519874e+00  1.99351501e+00  5.04255295e-04  2.96020508e-03
   4.97279835e+00  4.97460890e+00 -4.96920872e+00  1.99111891e+00]]


In [9]:
MissImputer = MissingImputer(ini_fill = True, model_reg = "randomforest", model_clf = "randomforest")
MissImputer

MissingImputer(cat_index=None, ini_fill=True, ini_strategy_clf=None,
        ini_strategy_reg=None, max_iter=10, model_clf='randomforest',
        model_reg='randomforest', tol=0.001, with_cat=False)

In [10]:
X_trans = MissImputer.fit(X).transform(X.copy())

fit:imputed_ini
[[ 3.          2.          7.          8.          2.          1.
  -3.          0.        ]
 [ 0.          5.          0.         -5.          0.          4.
  -4.         -1.        ]
 [ 1.5         3.5         0.          0.          5.          5.
  -5.          2.        ]
 [ 1.5         3.5         2.33333333  1.          2.33333333  3.33333333
  -4.          0.33333333]]
[[ 3.   2.   7.   8.   2.   1.  -3.   0. ]
 [ 0.   5.   0.  -5.   0.   4.  -4.  -1. ]
 [ 0.9  3.8  0.   0.   5.   5.  -5.   2. ]
 [ 0.9  4.4  0.7 -4.   2.   3.4 -4.  -0.2]]
transform:imputed_ini
[[ 3.          2.          7.          8.          2.          1.
  -3.          0.        ]
 [ 0.          5.          0.         -5.          0.          4.
  -4.         -1.        ]
 [ 1.5         3.5         0.          0.          5.          5.
  -5.          2.        ]
 [ 1.5         3.5         2.33333333  1.          2.33333333  3.33333333
  -4.          0.33333333]]


In [11]:
X_trans

array([[ 3. ,  2. ,  7. ,  8. ,  2. ,  1. , -3. ,  0. ],
       [ 0. ,  5. ,  0. , -5. ,  0. ,  4. , -4. , -1. ],
       [ 0.9,  3.8,  0. ,  0. ,  5. ,  5. , -5. ,  2. ],
       [ 0.9,  3.8,  0.7, -4. ,  2. ,  3.4, -3.8, -0.2]])

In [12]:
MissImputer = MissingImputer(ini_fill = True, model_reg = "lightgbm", model_clf = "lightgbm")
MissImputer

MissingImputer(cat_index=None, ini_fill=True, ini_strategy_clf=None,
        ini_strategy_reg=None, max_iter=10, model_clf='lightgbm',
        model_reg='lightgbm', tol=0.001, with_cat=False)

In [13]:
X_trans = MissImputer.fit(X).transform(X.copy())

LightGBMError: Cannot construct Dataset since there are not useful features.
It should be at least two unique rows.
If the num_row (num_data) is small, you can set min_data=1 and min_data_in_bin=1 to fix this.
Otherwise please make sure you are using the right dataset