In [1]:
import numpy as np 

from MissingImputer import MissingImputer

In [2]:
X = np.array([
    [3,0, np.nan, np.nan],  # odd: implicit zero
    [2,5, np.nan, np.nan],  # odd: explicit nonzero
    [7,0, 0, np.nan],    # even: average two zeros
    [8,-5, 0, np.nan],   # even: avg zero and neg
    [2,0, 5, np.nan],    # even: avg zero and pos
    [1,4, 5, np.nan],    # even: avg nonzeros
    [-3,-4, -5, np.nan],  # even: avg negatives
    [0,-1, 2, np.nan],   # even: crossing neg and pos
]).transpose()

In [3]:
MissImputer = MissingImputer(ini_fill = True, model_reg = "knn", model_clf = "knn")
MissImputer

MissingImputer(cat_index=None, ini_fill=True, ini_strategy_clf=None,
        ini_strategy_reg=None, max_iter=10, model_clf='knn',
        model_reg='knn', tol=0.001, with_cat=False)

In [4]:
X_trans = MissImputer.fit(X, model_params = {'regressor':{'n_neighbors':1}, 'classifier':{}}).transform(X.copy())

[[ 3.  2.  7.  8.  2.  1. -3.  0.]
 [ 0.  5.  0. -5.  0.  4. -4. -1.]
 [ 0.  5.  0.  0.  5.  5. -5.  2.]
 [ 0.  5.  0.  0.  5.  5. -5.  2.]]


In [5]:
X_trans

array([[ 3.,  2.,  7.,  8.,  2.,  1., -3.,  0.],
       [ 0.,  5.,  0., -5.,  0.,  4., -4., -1.],
       [ 0.,  5.,  0.,  0.,  5.,  5., -5.,  2.],
       [ 0.,  5.,  0.,  0.,  5.,  5., -5.,  2.]])

In [6]:
MissImputer = MissingImputer(ini_fill = True, model_reg = "xgboost", model_clf = "xgboost")
MissImputer

MissingImputer(cat_index=None, ini_fill=True, ini_strategy_clf=None,
        ini_strategy_reg=None, max_iter=10, model_clf='xgboost',
        model_reg='xgboost', tol=0.001, with_cat=False)

In [7]:
X_trans = MissImputer.fit(X).transform(X.copy())

[[ 3.00000000e+00  2.00000000e+00  7.00000000e+00  8.00000000e+00
   2.00000000e+00  1.00000000e+00 -3.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.00000000e+00  0.00000000e+00 -5.00000000e+00
   0.00000000e+00  4.00000000e+00 -4.00000000e+00 -1.00000000e+00]
 [ 2.98519874e+00  1.99351501e+00  0.00000000e+00  0.00000000e+00
   5.00000000e+00  5.00000000e+00 -5.00000000e+00  2.00000000e+00]
 [ 2.98519874e+00  1.99351501e+00  5.04255295e-04  2.96020508e-03
   4.97279835e+00  4.97460890e+00 -4.96920872e+00  1.99111891e+00]]


In [8]:
print(X_trans)

[[ 3.00000000e+00  2.00000000e+00  7.00000000e+00  8.00000000e+00
   2.00000000e+00  1.00000000e+00 -3.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.00000000e+00  0.00000000e+00 -5.00000000e+00
   0.00000000e+00  4.00000000e+00 -4.00000000e+00 -1.00000000e+00]
 [ 2.98519874e+00  1.99351501e+00  0.00000000e+00  0.00000000e+00
   5.00000000e+00  5.00000000e+00 -5.00000000e+00  2.00000000e+00]
 [ 2.98519874e+00  1.99351501e+00  5.04255295e-04  2.96020508e-03
   4.97279835e+00  4.97460890e+00 -4.96920872e+00  1.99111891e+00]]


In [45]:
MissImputer = MissingImputer(max_iter = 6, ini_fill = True, model_reg = "randomforest", model_clf = "randomforest")
MissImputer

MissingImputer(cat_index=None, ini_fill=True, ini_strategy_clf=None,
        ini_strategy_reg=None, max_iter=6, model_clf='randomforest',
        model_reg='randomforest', tol=0.001, with_cat=False)

In [46]:
X_trans = MissImputer.fit(X).transform(X.copy())

[[ 3.   2.   7.   8.   2.   1.  -3.   0. ]
 [ 0.   5.   0.  -5.   0.   4.  -4.  -1. ]
 [ 1.8  4.4  0.   0.   5.   5.  -5.   2. ]
 [ 1.8  4.4  0.7 -0.2  3.7  4.7 -4.1  0.8]]


In [47]:
X_trans

array([[ 3. ,  2. ,  7. ,  8. ,  2. ,  1. , -3. ,  0. ],
       [ 0. ,  5. ,  0. , -5. ,  0. ,  4. , -4. , -1. ],
       [ 1.8,  4.1,  0. ,  0. ,  5. ,  5. , -5. ,  2. ],
       [ 1.8,  4.1,  0.7, -0.2,  3.7,  4.7, -4.4,  1. ]])